# Generated by Django 5.1.4 on 2025-01-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='FilterModel',
        ),
    ]
